version: "3"
services:
  app:
    image: python:3-alpine
    container_name: weather-app
    # restart: unless-stopped # uncomment to production
    working_dir: /home/python/app
    #user: python
    volumes:
    - ./:/home/python/app
    command: ash -c "pip install --no-cache-dir -r requirements.txt && python script.py"